import { type IPublicChat } from "@chatty/shared/src/index";

export const features = [
  { icon: "group-chat", label: "Chatting" },
  { icon: "send-image-solid", label: "Media" },
  { icon: "privacy", label: "Privacy" },
  { icon: "speed", label: "Speed" },
];

export const chats: IPublicChat[] = [
  {
    id: 1,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Vivian&backgroundClor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "John Doe",
    lastMessage:
      "Hey, how are you?, How as your holiday been, hope all is well if so to God be the glory!",
    time: "10:30",
    lastMessageStatus: "unread",
    isOnline: true,
  },
  {
    id: 2,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Maria&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Bob Brown",
    lastMessage: "Thanks for the update.",
    time: "29/08/25",
    lastMessageStatus: "read",
    isOnline: false,
  },
  {
    id: 3,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Jude&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Bob Blue",
    lastMessage: "Thanks for the drink. It was really nice.",
    time: "29/08/25",
    lastMessageStatus: "read",
    isOnline: true,
  },
  {
    id: 4,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Aidan&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Jane Smith",
    lastMessage: "Let's catch up later!",
    time: "09:15",
    lastMessageStatus: "sent",
    isOnline: true,
  },
  {
    id: 5,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Luis&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Alice Johnson",
    lastMessage: "See you soon!",
    time: "Yesterday",
    lastMessageStatus: "received",
    isOnline: false,
  },
  {
    id: 6,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Caleb&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Mary Doe",
    lastMessage: "Hey, how are you?",
    time: "10:30",
    lastMessageStatus: "unread",
    isOnline: true,
  },
  {
    id: 7,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Christian&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Jane White",
    lastMessage: "Let's catch up later!",
    time: "09:15",
    lastMessageStatus: "sent",
    isOnline: false,
  },
  {
    id: 8,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Kingston&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Alexander Berry",
    lastMessage: "See you at the bar, come loaded!",
    time: "Yesterday",
    lastMessageStatus: "received",
    isOnline: true,
  },
  {
    id: 9,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Nolan&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Nolan Brown",
    lastMessage: "Thanks for the update.",
    time: "29/08/25",
    lastMessageStatus: "read",
    isOnline: false,
  },
  {
    id: 10,
    pic: "https://api.dicebear.com/9.x/adventurer/svg?seed=Amaya&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf",
    name: "Amaya Christian",
    lastMessage: "Thanks for the update.",
    time: "29/08/25",
    lastMessageStatus: "read",
    isOnline: false,
  },
];
